onejar: PromotePackagedVersion
main: org.litesoft.promotepackagedversion.PromotePackagedVersion

resources: 
- LICENSE

dependencies:
- ../LiteSoftAWS
- ../PackagedVersionCommonWithAWS

classpath:
- ../LiteSoftServerUtils/libs|**.jar
- ../LiteSoftAWS/libs|**.jar

